### ISSUE TITLE
Any plans to update for proto 3.9.1 and grpc 2.4.0  libs? 

### ISSUE THREAD

**Issue by lt-schmidt-jr** [salesforce/grpc-java-contrib#123]
Looks like the protocol buffers dependency are quite out of date, any plans to update to <grpc.version>1.24.0</grpc.version>
 <protoc.version>3.9.1</protoc.version>

**Comment by rmichela** [comment]
You should be able to use reactive-grpc with newer versions of gRPC. Are these dependencies causing problems?

**Comment by lt-schmidt-jr** [comment]
The specific problem I am encountering is adding an options java file compiled with proto 3.9, while attempting the write my custom plugin using jprotoc (thank you). 
Specifically **UnusedPrivateParameter** is not found in the older libs jprotoc uses.
Once I build jprotoc to newer proto java libs, it seems I can move forward

**Comment by rmichela** [comment]
👍 can you submit a PR?

**Comment by lt-schmidt-jr** [comment]
Will do, however, it is not fully baked in that it seems to break some of the other  (non-jproto-c) components

**Comment by rmichela** [comment]
i can look into it, too

**Comment by lt-schmidt-jr** [comment]
PR submitted https://github.com/salesforce/grpc-java-contrib/pull/124
Again, thank you for building this package.

**Comment by lt-schmidt-jr** [comment]
@rmichela would you mind releasing the changes, or let me know when you are planning next release?

**Comment by rmichela** [comment]
Released
