### ISSUE TITLE
Jprotoc: can't change output directory when using ProtocPlugin.debug()

### ISSUE THREAD

**Issue by sumio** [salesforce/grpc-java-contrib#140]
Files generated by `ProtocPlugin.debug()` based on `CodeGeneratorResponse` always resides in current working directory.
Would you add new `debug()` having 4 parameters to specify the directory of the generated files?

```java
public static void debug(
            @Nonnull List<Generator> generators,
            List<GeneratedExtension> extensions,
            @Nonnull String dumpPath,
            String outputDir) { ... }
```

It would be useful in case of calling `debug()` and verifying file output in test code.

**Comment by rmichela** [comment]
I added a proper unit testing workflow in 1.2.0.
