### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by badabapidas** [salesforce/grpc-java-contrib#142]
I wanted to give this libraries a try but while building its always failing due to dependencies. Checked out from master.

Error is
 Could not resolve dependencies for project com.salesforce.servicelibs:time-client-demo:jar:0.8.2-SNAPSHOT: Could not find artifact com.salesforce.servicelibs:grpc-contrib:jar:0.8.2-SNAPSHOT

This is a cutome library i gues which isnot available in the maven repo. Is there any way to resolve this>

Readme guide can be provided which will help the user to build the project and even the usage just a thought.

Anyway thanks

**Comment by SaiRepos** [comment]
@badabapidas I just triggered a [build](https://travis-ci.org/github/salesforce/grpc-java-contrib/builds/682059605) in Travis and it was successful. Make sure that you run `mvn clean install` from project root directory i.e `/grpc-java-contrib` so that all required artifacts are installed in your local maven repo as the pom in demo projects point to 0.8.2-SNAPSHOT of grpc-contrib which is not yet available in Maven central repo.

**Comment by badabapidas** [comment]
Thanks for the info. With some chekstyle and javadoc changes build is passing now. I am trying to start the demo server and client for TimeService as given in the readme
java -jar TimeService.jar --port 3333 but getting the following error. Any help?? Am I missing any configuration

2020-07-19 01:52:50.607 ERROR 28716 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grpcServerHost' defined in com.salesforce.servicelibs.timeserver.TimeServer: Unsatisfied dependency expressed through method 'grpcServerHost' parameter 0; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: ""

**Comment by SaiRepos** [comment]
@badabapidas it needs to be `--port=3333`. you missed `=` here

**Comment by badabapidas** [comment]
Thanks for the pointer. Its working now.
