### ISSUE TITLE
Invalid output file name for  insertion point during debug

### ISSUE THREAD

**Issue by jvmlet** [salesforce/grpc-java-contrib#170]
I'm on  latest version `1.2.0`, see [this ](https://github.com/salesforce/grpc-java-contrib/blob/79aeea46a61b9f3d724a172ab29374931c02fa7c/jprotoc/jprotoc/src/main/java/com/salesforce/jprotoc/ProtocPlugin.java#L160)
![image](https://user-images.githubusercontent.com/6664858/132974118-f62db125-4be4-401c-99e9-4025051360c8.png)

The next call to `Files.createParentDirs(outFile);`  at line `167` fails with 
```
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
```

**Comment by rmichela** [comment]
What OS are you using? Cursory searching of that error suggests Windows.

**Comment by jvmlet** [comment]
It's windows indeed, but the implementation is buggy anyway. `getNameWithoutExtension` cuts the full path and dot character before `java` is missing. So, while it might not throw the exception in Linux environment, it behaves not the way it should....
