### ISSUE TITLE
Creating Gradle build files

### ISSUE THREAD

**Issue by noel-yap** [salesforce/grpc-java-contrib#21]
I'm creating Gradle build files so we can better support `jprotoc` within our environment. Everything works at this point except for the symbol `GreeterGrpc8` not being found while building `jprotoc-test`. How is this generated?

**Comment by rmichela** [comment]
`GreeterGrpc8` is generated by executing the `com.salesforce.jprotoc.jdk8.Jdk8Generator` plugin during Maven's `generate-test-sources` lifecycle stage.

https://github.com/salesforce/grpc-java-contrib/blob/master/jprotoc-test/pom.xml#L101
