### ISSUE TITLE
Add a field/variable at code generation

### ISSUE THREAD

**Issue by 313hemant313** [salesforce/grpc-java-contrib#244]
Using Jprotoc, wanted to check if we can safely add a field at the time of code generation.

Like adding List<SomeThingJsonPojo> jsonPojoList, while supporting safe data transfer.

**Comment by 313hemant313** [comment]
@rmichela Can you please guide.

**Comment by rmichela** [comment]
JProtoc cannot modify the code generated directly by protoc. 

You can, however, author a custom code generator that will run alongside protoc's generator and generate any additional source files or classes you'd like.

**Comment by 313hemant313** [comment]
@rmichela Any sample code to do the same ? any reference ?
