### ISSUE TITLE
Generated stub refers to class name with incorrect case

### ISSUE THREAD

**Issue by saturnism** [salesforce/grpc-java-contrib#34]
E.g., if I have a proto file like `StreamingExample.proto", the generator generated imports with `com.example.server.streaming.Streamingexample`

**Comment by rmichela** [comment]
Which generator? Jdk8, or RxGrpc? Also, do you have `option java_package` set in your .proto file?

**Comment by rmichela** [comment]
Could not reproduce. Please update with more details if this is still a problem.
