### ISSUE TITLE
Publish executables for rxgrpc

### ISSUE THREAD

**Issue by cbornet** [salesforce/grpc-java-contrib#35]
The gradle plugin doesn't seem to support native JVM plugins.
Is it possible to build the executables so that we can use the standard way ?

**Comment by rmichela** [comment]
I'm not familiar with the gradle protoc plugin. What do you mean by "the standard way"?

The maven protoc plugin creates a dynamic shell script or windows exe at runtime in order to invoke java plugins. Does the gradle protoc plugin not do this?

**Comment by cbornet** [comment]
Yes the gradle plugin seems to only support calling an exe directly, not creating it an runtime from a jar.
I'm not an expert in gradle but I am integrating your generator in a [JHipster](http://www.jhipster.tech/) module so I need to support the gradle option.

**Comment by cbornet** [comment]
I found [this issue](https://github.com/google/protobuf-gradle-plugin/issues/31) which seems to say that it's possible to use executable jars.

**Comment by rmichela** [comment]
When you get it working, can you share a link to the source? I'll update the jprotoc documentation accordingly.

**Comment by venth** [comment]
Gradle plugin seems to download executable artifact directly from maven repo:

> https://repo1.maven.org/maven2/com/salesforce/servicelibs/rxgrpc/0.6.1/rxgrpc-0.6.1-osx-x86_64.exe

Example configuration for gradle:
```
buildscript {
    ext {
        ver = [
                protobufPlugin            : "0.8.1",
        ]
    }

    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath("com.google.protobuf:protobuf-gradle-plugin:${ver.protobufPlugin}")
    }
}

apply plugin: 'com.google.protobuf'
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${ver.protobuf}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${ver.grpc}"
        }
        rxgrpc {
            artifact = "com.salesforce.servicelibs:rxgrpc:${ver.rxgrpc}"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {
                // To generate deprecated interfaces and static bindService method,
                // turn the enable_deprecated option to true below:
                option 'enable_deprecated=false'
            }
            rxgrpc {}
        }
    }
}

```

**Comment by dadadom** [comment]
@venth : Is this a working example of yours? I tried the same (with the reactor plugin, though) and don't manage to integrate the plugin into our gradle build.

**Comment by venth** [comment]
@dadadom My bad. Unfortunately I was able to make gradle download the plugin. Still it cannot be executed :( I believe that either there is a need to introduce a script to conform current gradle protobuf functionality or convince guys from protobuf plugin to add functionality of execution pure java plugin.

**Comment by venth** [comment]
I’ve added the insight of my finding in the issue in gradle protobuf plugin: https://github.com/google/protobuf-gradle-plugin/issues/168

**Comment by rmichela** [comment]
Further discussion and implementation is happening at https://github.com/salesforce/reactive-grpc/issues/21
